(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const STORAGE_PROJECT="wsw:sketch:v3", STORAGE_BRUSHES="wsw:brushes:v3";
const KIND_ORDER=["ink","dry","dark","light","cinnabar","gold","vine","yunlei"];
const KIND_NAMES={ink:"松烟",dry:"飞白",dark:"浓墨",light:"淡墨",cinnabar:"朱砂",gold:"金线",vine:"缠枝",yunlei:"云雷"};
const PAPER_PRESETS=[
  {id:"xuan",name:"宣纸",color:"#f5eddf"},{id:"moon",name:"月白",color:"#f5f7f1"},{id:"jade",name:"青白",color:"#e7efeb"},{id:"warm",name:"米宣",color:"#eee1cd"},{id:"ink",name:"松烟",color:"#202422"}
];
const PRESETS=[
  {id:"songyan",name:"松烟墨",kind:"ink",color:"#2f2a27",size:12,opacity:.93,spacing:18,jitter:.04,parentHash:0},
  {id:"feibai",name:"飞白",kind:"dry",color:"#332d29",size:19,opacity:.88,spacing:17,jitter:.32,parentHash:0},
  {id:"nongmo",name:"浓墨",kind:"dark",color:"#201d1b",size:24,opacity:.97,spacing:18,jitter:.03,parentHash:0},
  {id:"danmo",name:"淡墨",kind:"light",color:"#4c4a46",size:28,opacity:.28,spacing:18,jitter:.04,parentHash:0},
  {id:"zhusha",name:"朱砂",kind:"cinnabar",color:"#a64334",size:13,opacity:.92,spacing:18,jitter:.02,parentHash:0},
  {id:"jinxian",name:"金线",kind:"gold",color:"#b58a48",size:8,opacity:.92,spacing:18,jitter:.01,parentHash:0},
  {id:"chanzhi",name:"缠枝",kind:"vine",color:"#355e50",size:18,opacity:.9,spacing:29,jitter:.12,parentHash:0},
  {id:"yunlei",name:"云雷",kind:"yunlei",color:"#8b4236",size:18,opacity:.9,spacing:34,jitter:.05,parentHash:0}
];
const cloneBrush=b=>({id:b.id||"custom",name:b.name||KIND_NAMES[b.kind]||"自造画笔",kind:KIND_ORDER.includes(b.kind)?b.kind:"ink",color:/^#[0-9a-f]{6}$/i.test(b.color||"")?b.color:"#2f2a27",size:clamp(Number(b.size)||12,2,64),opacity:clamp(Number(b.opacity)||.9,.05,1),spacing:clamp(Number(b.spacing)||20,6,120),jitter:clamp(Number(b.jitter)||0,0,1),parentHash:(Number(b.parentHash)||0)>>>0});

const committed=$("#committed-canvas"), preview=$("#preview-canvas"), cctx=committed.getContext("2d"), pctx=preview.getContext("2d");
const viewport=$("#canvas-viewport"), scene=$("#paper-scene");
const state={
  strokes:[], undo:[], redo:[], customBrushes:[], activeBrush:cloneBrush(PRESETS[0]), mode:"draw", background:PAPER_PRESETS[0],
  current:null, pointers:new Map(), gesture:null, view:{zoom:1,tx:0,ty:0}, paperCss:{w:0,h:0}, raf:0, saveTimer:0, erasingIds:new Set(), exporting:false
};

function toast(text){const el=$("#toast");el.textContent=text;el.classList.add("show");clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove("show"),1450)}
function deepStroke(s){return{id:s.id,seed:s.seed,brush:cloneBrush(s.brush),points:s.points.map(p=>({x:p.x,y:p.y,p:p.p}))}}
function round4(n){return Math.round(n*10000)/10000}
function serializeStroke(s){return{id:s.id,seed:s.seed,brush:cloneBrush(s.brush),points:s.points.map(p=>[round4(p.x),round4(p.y),Math.round(clamp(p.p,.05,1)*255)])}}
function deserializeStroke(s){return{id:s.id||uid(),seed:(s.seed||1)>>>0,brush:cloneBrush(s.brush||PRESETS[0]),points:(s.points||[]).map(p=>Array.isArray(p)?{x:Number(p[0]),y:Number(p[1]),p:clamp(Number(p[2]??200)/255,.05,1)}:{x:Number(p.x),y:Number(p.y),p:clamp(Number(p.p)||.7,.05,1)})}}
function scheduleSave(){clearTimeout(state.saveTimer);state.saveTimer=setTimeout(saveProject,260)}
function saveProject(){try{localStorage.setItem(STORAGE_PROJECT,JSON.stringify({v:3,background:state.background.id,strokes:state.strokes.map(serializeStroke),activeBrush:cloneBrush(state.activeBrush)}));localStorage.setItem(STORAGE_BRUSHES,JSON.stringify(state.customBrushes.slice(-80)))}catch(e){console.warn("local save failed",e)}}
function loadProject(){try{const bs=JSON.parse(localStorage.getItem(STORAGE_BRUSHES)||"[]");state.customBrushes=Array.isArray(bs)?bs.map(x=>({name:String(x.name||"我的画笔"),seed:String(x.seed||""),brush:cloneBrush(x.brush||decodeBrush(x.seed))})).filter(x=>x.seed.startsWith("WB2-")):[];const raw=JSON.parse(localStorage.getItem(STORAGE_PROJECT)||"null");if(raw?.v===3){state.background=PAPER_PRESETS.find(x=>x.id===raw.background)||PAPER_PRESETS[0];state.strokes=Array.isArray(raw.strokes)?raw.strokes.map(deserializeStroke).filter(s=>s.points.length>1):[];if(raw.activeBrush)state.activeBrush=cloneBrush(raw.activeBrush)}}catch(e){console.warn("local restore failed",e)}}

function uid(){return`st_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`}
function fnv(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=seed|0;return()=>{a=(a+0x6d2b79f5)|0;let t=Math.imul(a^(a>>>15),1|a);t^=t+Math.imul(t^(t>>>7),61|t);return((t^(t>>>14))>>>0)/4294967296}}
function hexRgb(hex){const n=parseInt(hex.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255]}
function rgba(hex,a){const [r,g,b]=hexRgb(hex);return`rgba(${r},${g},${b},${clamp(a,0,1)})`}
function crc16(bytes){let crc=0xffff;for(const b of bytes){crc^=b<<8;for(let i=0;i<8;i++)crc=(crc&0x8000)?((crc<<1)^0x1021)&0xffff:(crc<<1)&0xffff}return crc}
function b64url(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function fromB64url(text){const s=text.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((text.length+3)%4);const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function encodeBrush(input){const b=cloneBrush(input),bytes=new Uint8Array(15),[r,g,bl]=hexRgb(b.color);bytes[0]=2;bytes[1]=KIND_ORDER.indexOf(b.kind);bytes[2]=r;bytes[3]=g;bytes[4]=bl;bytes[5]=Math.round(b.size);bytes[6]=Math.round(b.opacity*255);bytes[7]=Math.round(b.spacing);bytes[8]=Math.round(b.jitter*100);const ph=b.parentHash>>>0;bytes[9]=(ph>>>24)&255;bytes[10]=(ph>>>16)&255;bytes[11]=(ph>>>8)&255;bytes[12]=ph&255;const crc=crc16(bytes.slice(0,13));bytes[13]=(crc>>>8)&255;bytes[14]=crc&255;return`WB2-${b64url(bytes)}`}
function decodeBrush(code){const text=String(code||"").trim();if(!/^WB2-[A-Za-z0-9_-]{18,40}$/.test(text))throw new Error("这不是有效的 WB2 画笔种子");const bytes=fromB64url(text.slice(4));if(bytes.length!==15||bytes[0]!==2)throw new Error("画笔种子版本不支持");const crc=(bytes[13]<<8)|bytes[14];if(crc16(bytes.slice(0,13))!==crc)throw new Error("画笔种子校验失败");const kind=KIND_ORDER[bytes[1]];if(!kind)throw new Error("画笔类型不存在");const color=`#${[bytes[2],bytes[3],bytes[4]].map(x=>x.toString(16).padStart(2,"0")).join("")}`;const parentHash=((bytes[9]<<24)>>>0)|(bytes[10]<<16)|(bytes[11]<<8)|bytes[12];return cloneBrush({id:"shared",name:`共享${KIND_NAMES[kind]}笔`,kind,color,size:clamp(bytes[5],2,64),opacity:clamp(bytes[6]/255,.05,1),spacing:clamp(bytes[7],6,120),jitter:clamp(bytes[8]/100,0,1),parentHash:parentHash>>>0})}
function fingerprint(code){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let n=fnv(code),out="";for(let i=0;i<5;i++){out+=chars[n&31];n=(n>>>5)^(n*33)}return out}

function setPaperBackground(){scene.style.setProperty("--canvas-bg",state.background.color)}
function fitPaper(){const r=viewport.getBoundingClientRect(),pad=26;let h=Math.max(220,r.height-pad*2),w=h*.75;if(w>r.width-pad*2){w=Math.max(180,r.width-pad*2);h=w/0.75}state.paperCss={w,h};scene.style.width=`${w}px`;scene.style.height=`${h}px`;const dpr=Math.min(window.devicePixelRatio||1,2.5),bw=Math.round(clamp(w*dpr,540,900)),bh=Math.round(bw/0.75);if(committed.width!==bw||committed.height!==bh){committed.width=preview.width=bw;committed.height=preview.height=bh;renderCommitted()}resetView(false)}
function applyView(){const v=state.view;scene.style.transform=`translate(-50%,-50%) translate(${v.tx}px,${v.ty}px) scale(${v.zoom})`;$("#zoom-badge").textContent=`${Math.round(v.zoom*100)}%`}
function resetView(show=true){state.view={zoom:1,tx:0,ty:0};applyView();if(show)toast("画布已适应屏幕")}
function setCanvasSizeFromResize(){fitPaper();updateUI()}

function clearCanvas(ctx){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,ctx.canvas.width,ctx.canvas.height)}
function toPx(points,w,h){return points.map(p=>({x:p.x*w,y:p.y*h,p:p.p}))}
function drawVariableLine(ctx,stroke,w,h,opts={}){const pts=toPx(stroke.points,w,h);if(pts.length<2)return;const b=stroke.brush,scale=w/375,base=b.size*scale,alpha=b.opacity*(opts.alphaMul??1);ctx.save();ctx.lineCap="round";ctx.lineJoin="round";if(opts.bleed){ctx.strokeStyle=rgba(b.color,alpha*.11);for(let i=1;i<pts.length;i++){const a=pts[i-1],q=pts[i];ctx.lineWidth=base*(.92+.58*((a.p+q.p)/2))*1.42;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}ctx.strokeStyle=rgba(b.color,alpha);for(let i=1;i<pts.length;i++){const a=pts[i-1],q=pts[i],pressure=.42+.72*((a.p+q.p)/2);ctx.lineWidth=Math.max(.8,base*pressure);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(q.x,q.y);ctx.stroke()}ctx.restore()}
function drawDry(ctx,stroke,w,h){const pts=toPx(stroke.points,w,h);if(pts.length<2)return;const b=stroke.brush,scale=w/375,base=b.size*scale,rand=rng(stroke.seed||1);ctx.save();ctx.lineCap="round";for(let strand=0;strand<3;strand++){for(let i=1;i<pts.length;i++){const a=pts[i-1],q=pts[i];if(rand()<(.18+b.jitter*.46))continue;const dx=q.x-a.x,dy=q.y-a.y,len=Math.max(1,Math.hypot(dx,dy)),nx=-dy/len,ny=dx/len,off=(strand-1)*base*.16+(rand()-.5)*base*.18;ctx.strokeStyle=rgba(b.color,b.opacity*(strand===1?.72:.38)*(0.7+rand()*.3));ctx.lineWidth=Math.max(.7,base*(.16+rand()*.22)*(0.6+(a.p+q.p)*.25));ctx.beginPath();ctx.moveTo(a.x+nx*off,a.y+ny*off);ctx.lineTo(q.x+nx*off,q.y+ny*off);ctx.stroke()}}ctx.restore()}
function sampleAlong(points,w,h,spacing){const pts=toPx(points,w,h),out=[];if(pts.length<2)return out;let carry=0;for(let i=1;i<pts.length;i++){let a=pts[i-1],b=pts[i],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);if(len<.01)continue;let pos=spacing-carry;while(pos<=len){const t=pos/len;out.push({x:lerp(a.x,b.x,t),y:lerp(a.y,b.y,t),angle:Math.atan2(dy,dx),i:out.length});pos+=spacing}carry=(carry+len)%spacing}return out}
function drawVine(ctx,stroke,w,h){const b=stroke.brush,scale=w/375;baseLine();function baseLine(){const slim={...stroke,brush:{...b,size:Math.max(2,b.size*.18),opacity:b.opacity*.72}};drawVariableLine(ctx,slim,w,h)}const spacing=Math.max(12,b.spacing*scale),samples=sampleAlong(stroke.points,w,h,spacing),size=b.size*scale*.72,rand=rng(stroke.seed||1);ctx.save();ctx.fillStyle=rgba(b.color,b.opacity*.84);ctx.strokeStyle=rgba(b.color,b.opacity*.9);ctx.lineWidth=Math.max(1,scale*1.1);samples.forEach((s,i)=>{const side=i%2?1:-1,j=(rand()-.5)*b.jitter*.8;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.angle+side*(.72+j));ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(size*.42,-size*.34,size*.82,-size*.08);ctx.quadraticCurveTo(size*.45,size*.28,0,0);ctx.fill();ctx.restore();if(i%3===1){ctx.fillStyle=rgba("#b1844b",b.opacity*.85);ctx.beginPath();ctx.arc(s.x,s.y,Math.max(1.3,size*.12),0,Math.PI*2);ctx.fill();ctx.fillStyle=rgba(b.color,b.opacity*.84)}});ctx.restore()}
function drawYunlei(ctx,stroke,w,h){const b=stroke.brush,scale=w/375,spacing=Math.max(15,b.spacing*scale),samples=sampleAlong(stroke.points,w,h,spacing),size=b.size*scale*.75;ctx.save();ctx.strokeStyle=rgba(b.color,b.opacity);ctx.lineWidth=Math.max(1,scale*1.25);ctx.lineCap="square";ctx.lineJoin="miter";for(const s of samples){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.angle);ctx.beginPath();ctx.moveTo(-size*.56,size*.42);ctx.lineTo(-size*.56,-size*.42);ctx.lineTo(size*.5,-size*.42);ctx.lineTo(size*.5,size*.35);ctx.lineTo(-size*.2,size*.35);ctx.lineTo(-size*.2,-size*.12);ctx.lineTo(size*.17,-size*.12);ctx.lineTo(size*.17,size*.12);ctx.lineTo(0,size*.12);ctx.stroke();ctx.restore()}ctx.restore()}
function renderStroke(ctx,stroke,w,h){if(!stroke||stroke.points.length<2)return;switch(stroke.brush.kind){case"dry":drawDry(ctx,stroke,w,h);break;case"light":drawVariableLine(ctx,stroke,w,h,{alphaMul:.75,bleed:true});break;case"dark":drawVariableLine(ctx,stroke,w,h,{bleed:true});break;case"cinnabar":drawVariableLine(ctx,stroke,w,h,{bleed:true});break;case"gold":ctx.save();ctx.shadowColor="rgba(110,78,28,.2)";ctx.shadowBlur=Math.max(1,w/700);drawVariableLine(ctx,stroke,w,h);ctx.restore();break;case"vine":drawVine(ctx,stroke,w,h);break;case"yunlei":drawYunlei(ctx,stroke,w,h);break;default:drawVariableLine(ctx,stroke,w,h,{bleed:true})}}
function renderCommitted(){clearCanvas(cctx);for(const s of state.strokes)renderStroke(cctx,s,committed.width,committed.height);updateUI()}
function renderPreview(){state.raf=0;clearCanvas(pctx);if(state.current)renderStroke(pctx,state.current,preview.width,preview.height)}
function schedulePreview(){if(!state.raf)state.raf=requestAnimationFrame(renderPreview)}

function pointFromEvent(e){const r=scene.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width,-.045,1.045),y:clamp((e.clientY-r.top)/r.height,-.045,1.045),clientX:e.clientX,clientY:e.clientY,time:performance.now(),rawPressure:e.pressure||0}}
function startStroke(e,p){state.current={id:uid(),seed:(Date.now()^Math.floor(Math.random()*0xffffffff))>>>0,brush:cloneBrush(state.activeBrush),points:[{x:p.x,y:p.y,p:e.pointerType==="pen"&&p.rawPressure>0?clamp(p.rawPressure,.1,1):.72}]};state.current.pointerId=e.pointerId;state.current.lastMeta=p;$("#empty-hint").classList.add("hide");schedulePreview()}
function appendStroke(e,p){const s=state.current;if(!s||s.pointerId!==e.pointerId)return;const prev=s.lastMeta,rect=scene.getBoundingClientRect(),dist=Math.hypot((p.x-prev.x)*rect.width,(p.y-prev.y)*rect.height);if(dist<1.4)return;const dt=Math.max(1,p.time-prev.time),speed=dist/dt,pressure=e.pointerType==="pen"&&p.rawPressure>0?clamp(p.rawPressure,.08,1):clamp(1.03-speed*.17,.34,1);s.points.push({x:p.x,y:p.y,p:pressure});s.lastMeta=p;schedulePreview()}
function simplifyPoints(points){if(points.length<=3)return points.map(({x,y,p})=>({x,y,p}));const out=[points[0]],min=.0017;for(let i=1;i<points.length-1;i++){const a=out[out.length-1],b=points[i];if(Math.hypot(b.x-a.x,b.y-a.y)>=min)out.push(b)}out.push(points.at(-1));return out.map(({x,y,p})=>({x,y,p}))}
function commitStroke(){const s=state.current;if(!s)return;state.current=null;clearCanvas(pctx);const pts=simplifyPoints(s.points);if(pts.length<2)return;s.points=pts;delete s.pointerId;delete s.lastMeta;state.strokes.push(s);state.undo.push({type:"add",stroke:deepStroke(s)});state.redo.length=0;renderCommitted();scheduleSave()}
function cancelStroke(){state.current=null;clearCanvas(pctx)}
function hitStroke(p){const r=scene.getBoundingClientRect(),threshold=clamp(20/r.width,.018,.06);for(let i=state.strokes.length-1;i>=0;i--){const s=state.strokes[i];for(const q of s.points){if(Math.hypot(q.x-p.x,q.y-p.y)<threshold)return i}}return-1}
function eraseAt(p){const i=hitStroke(p);if(i<0)return;const s=state.strokes[i];if(state.erasingIds.has(s.id))return;state.erasingIds.add(s.id);state.strokes.splice(i,1);state.undo.push({type:"remove",stroke:deepStroke(s),index:i});state.redo.length=0;renderCommitted();scheduleSave();navigator.vibrate?.(5)}
function beginGesture(){const arr=[...state.pointers.values()].slice(0,2),a=arr[0],b=arr[1],center={x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2},dist=Math.max(10,Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY));state.gesture={dist,center,zoom:state.view.zoom,tx:state.view.tx,ty:state.view.ty};cancelStroke()}
function updateGesture(){if(state.pointers.size<2||!state.gesture)return;const [a,b]=[...state.pointers.values()].slice(0,2),center={x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2},dist=Math.max(10,Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)),g=state.gesture;state.view.zoom=clamp(g.zoom*(dist/g.dist),.5,4);state.view.tx=g.tx+(center.x-g.center.x);state.view.ty=g.ty+(center.y-g.center.y);applyView()}
function onPointerDown(e){e.preventDefault();viewport.setPointerCapture?.(e.pointerId);const p=pointFromEvent(e);state.pointers.set(e.pointerId,p);if(state.pointers.size>=2){beginGesture();return}const inside=p.x>=-.045&&p.x<=1.045&&p.y>=-.045&&p.y<=1.045;if(!inside)return;if(state.mode==="erase"){state.erasingIds.clear();eraseAt(p)}else startStroke(e,p)}
function onPointerMove(e){if(!state.pointers.has(e.pointerId))return;e.preventDefault();const p=pointFromEvent(e);state.pointers.set(e.pointerId,p);if(state.pointers.size>=2){updateGesture();return}if(state.mode==="erase")eraseAt(p);else appendStroke(e,p)}
function onPointerUp(e){if(!state.pointers.has(e.pointerId))return;e.preventDefault();const wasTwo=state.pointers.size>=2;state.pointers.delete(e.pointerId);if(wasTwo){state.gesture=null;cancelStroke()}else if(state.mode==="draw")commitStroke();state.erasingIds.clear()}
viewport.addEventListener("pointerdown",onPointerDown,{passive:false});viewport.addEventListener("pointermove",onPointerMove,{passive:false});viewport.addEventListener("pointerup",onPointerUp,{passive:false});viewport.addEventListener("pointercancel",onPointerUp,{passive:false});

function applyUndo(action,reverse){if(action.type==="add"){if(reverse){const i=state.strokes.findIndex(s=>s.id===action.stroke.id);if(i>=0)state.strokes.splice(i,1)}else state.strokes.push(deepStroke(action.stroke))}else if(action.type==="remove"){if(reverse)state.strokes.splice(clamp(action.index,0,state.strokes.length),0,deepStroke(action.stroke));else{const i=state.strokes.findIndex(s=>s.id===action.stroke.id);if(i>=0)state.strokes.splice(i,1)}}else if(action.type==="clear"){state.strokes=reverse?action.strokes.map(deepStroke):[]}}
function undo(){const a=state.undo.pop();if(!a)return;applyUndo(a,true);state.redo.push(a);renderCommitted();scheduleSave()}
function redo(){const a=state.redo.pop();if(!a)return;applyUndo(a,false);state.undo.push(a);renderCommitted();scheduleSave()}
function clearArtwork(){if(!state.strokes.length)return;if(!confirm("清空整张画布？这一步可以再撤销一次。"))return;state.undo.push({type:"clear",strokes:state.strokes.map(deepStroke)});state.redo.length=0;state.strokes=[];renderCommitted();scheduleSave();closeSheet();toast("画布已清空")}

function updateUI(){$("#undo").disabled=!state.undo.length;$("#redo").disabled=!state.redo.length;$("#eraser").classList.toggle("active",state.mode==="erase");$("#open-brushes").classList.toggle("active",state.mode==="draw");$("#brush-name").textContent=state.activeBrush.name;$("#brush-dot").style.background=state.activeBrush.color;$("#color-dot").style.background=state.activeBrush.color;$("#quick-color").value=state.activeBrush.color;$("#color-label").textContent=state.activeBrush.color.toUpperCase();$("#size-label").textContent=Math.round(state.activeBrush.size);$("#empty-hint").classList.toggle("hide",state.strokes.length>0||!!state.current);setPaperBackground()}
function setActiveBrush(input,name){state.activeBrush=cloneBrush({...input,name:name||input.name});state.mode="draw";updateUI();scheduleSave()}
function setMode(mode){state.mode=mode;updateUI();toast(mode==="erase"?"橡皮：划过一笔即可整笔擦除":"继续画吧")}

function openSheet(kind){const titles={brush:["BRUSH BOX","国风画笔"],size:["BRUSH FEEL","笔触"],more:["CANVAS","画布"],export:["EXPORT","高清导出"],editor:["BRUSH MAKER","创建画笔"],import:["BRUSH SEED","导入画笔种子"]};$("#sheet-kicker").textContent=titles[kind][0];$("#sheet-title").textContent=titles[kind][1];const body=$("#sheet-body");if(kind==="brush")renderBrushSheet(body);if(kind==="size")renderSizeSheet(body);if(kind==="more")renderMoreSheet(body);if(kind==="export")renderExportSheet(body);if(kind==="editor")renderBrushEditor(body);if(kind==="import")renderImport(body);$("#sheet-backdrop").hidden=false;requestAnimationFrame(()=>$("#bottom-sheet").classList.add("open"));$("#bottom-sheet").setAttribute("aria-hidden","false")}
function closeSheet(){$("#bottom-sheet").classList.remove("open");$("#bottom-sheet").setAttribute("aria-hidden","true");setTimeout(()=>{$("#sheet-backdrop").hidden=true},240)}
$("#close-sheet").onclick=closeSheet;$("#sheet-backdrop").onclick=closeSheet;
function brushIcon(kind){return{ink:"墨",dry:"飞",dark:"浓",light:"淡",cinnabar:"朱",gold:"金",vine:"枝",yunlei:"雷"}[kind]||"笔"}
function brushCard(b,extra=""){const active=encodeBrush(b)===encodeBrush(state.activeBrush);return`<button class="brush-card ${active?"active":""}" ${extra}><span class="swatch" style="background:${b.color}">${brushIcon(b.kind)}</span><strong>${esc(b.name)}</strong><small>${KIND_NAMES[b.kind]} · ${Math.round(b.size)}</small></button>`}
function renderBrushSheet(root){root.innerHTML=`<section class="section"><div class="section-title"><strong>国风画笔</strong><small>点一下就能画</small></div><div class="brush-grid">${PRESETS.map((b,i)=>brushCard(b,`data-preset="${i}"`)).join("")}</div></section><section class="section"><div class="section-title"><strong>我的画笔</strong><small>${state.customBrushes.length} 支</small></div>${state.customBrushes.length?`<div class="brush-grid">${state.customBrushes.slice(-12).reverse().map((x,i)=>brushCard({...x.brush,name:x.name},`data-custom="${state.customBrushes.length-1-i}"`)).join("")}</div>`:`<div class="empty">还没有自定义画笔。先调一支自己的。</div>`}<div class="sheet-actions"><button class="secondary" id="make-brush">＋ 创建画笔</button><button class="secondary" id="import-brush">⌘ 导入种子</button></div></section><button class="wide-btn" id="share-current-brush">复制当前画笔种子</button>`;$$('[data-preset]',root).forEach(b=>b.onclick=()=>{const p=PRESETS[Number(b.dataset.preset)];setActiveBrush(p,p.name);closeSheet()});$$('[data-custom]',root).forEach(b=>b.onclick=()=>{const x=state.customBrushes[Number(b.dataset.custom)];setActiveBrush(x.brush,x.name);closeSheet()});$("#make-brush",root).onclick=()=>openSheet("editor");$("#import-brush",root).onclick=()=>openSheet("import");$("#share-current-brush",root).onclick=()=>shareBrush(state.activeBrush)}
function renderSizeSheet(root){const b=state.activeBrush;root.innerHTML=`<section class="section"><div class="control"><label>粗细</label><input id="brush-size" type="range" min="2" max="64" step="1" value="${b.size}"><output id="brush-size-out">${Math.round(b.size)}</output></div><div class="control"><label>透明度</label><input id="brush-opacity" type="range" min="5" max="100" step="1" value="${Math.round(b.opacity*100)}"><output id="brush-opacity-out">${Math.round(b.opacity*100)}%</output></div>${["vine","yunlei"].includes(b.kind)?`<div class="control"><label>间距</label><input id="brush-spacing" type="range" min="10" max="80" value="${b.spacing}"><output id="brush-spacing-out">${Math.round(b.spacing)}</output></div>`:""}<p class="tip">修改只影响接下来画的新笔；已经画好的笔迹保持原样。</p></section><div class="sheet-actions"><button class="secondary" id="edit-brush">更多画笔设置</button><button class="primary" id="save-adjusted">保存为我的画笔</button></div>`;$("#brush-size",root).oninput=e=>{state.activeBrush.size=Number(e.target.value);$("#brush-size-out",root).textContent=e.target.value;updateUI()};$("#brush-opacity",root).oninput=e=>{state.activeBrush.opacity=Number(e.target.value)/100;$("#brush-opacity-out",root).textContent=`${e.target.value}%`};const spacing=$("#brush-spacing",root);if(spacing)spacing.oninput=e=>{state.activeBrush.spacing=Number(e.target.value);$("#brush-spacing-out",root).textContent=e.target.value};$("#edit-brush",root).onclick=()=>openSheet("editor");$("#save-adjusted",root).onclick=()=>saveCustomBrush({...state.activeBrush,name:`我的${KIND_NAMES[state.activeBrush.kind]}笔`})}
function renderMoreSheet(root){root.innerHTML=`<section class="section"><div class="section-title"><strong>纸张</strong><small>最终导出边界就是这张纸</small></div><div class="palette-row">${PAPER_PRESETS.map(p=>`<button class="paper-option" data-paper="${p.id}"><span style="background:${p.color}"></span><small>${p.name}</small></button>`).join("")}</div></section><section class="section"><div class="sheet-actions"><button class="secondary" id="fit-sheet">适应画布</button><button class="secondary" id="about-app">使用说明</button></div><button class="danger wide-btn" id="clear-art">清空画布</button><p class="tip">画布固定为 3:4。绘画时允许笔迹自然越过纸边，导出会自动裁在纸张边界内。</p></section>`;$$('[data-paper]',root).forEach(b=>b.onclick=()=>{state.background=PAPER_PRESETS.find(p=>p.id===b.dataset.paper)||PAPER_PRESETS[0];setPaperBackground();scheduleSave();toast(`已换成${state.background.name}`)});$("#fit-sheet",root).onclick=()=>{resetView();closeSheet()};$("#clear-art",root).onclick=clearArtwork;$("#about-app",root).onclick=()=>{$("#info-dialog").showModal();closeSheet()}}
function renderExportSheet(root){root.innerHTML=`<section class="section"><div class="export-options"><button class="export-card" data-export="1440"><strong>高清保存</strong><small>3:4 小红书主图</small><b>1440 × 1920</b></button><button class="export-card" data-export="2160"><strong>超清保存</strong><small>适合放大与二次裁切</small><b>2160 × 2880</b></button></div><button class="wide-btn" id="system-share">生成高清图并分享</button><p class="tip">平时只用轻量预览画布保证流畅；点击导出时才临时高精度重绘全部笔迹，所以作品不会因为手机屏幕小而糊。</p></section>`;$$('[data-export]',root).forEach(b=>b.onclick=()=>exportArtwork(Number(b.dataset.export),false));$("#system-share",root).onclick=()=>exportArtwork(1440,true)}
function renderBrushEditor(root){const source=cloneBrush(state.activeBrush),parent=fnv(encodeBrush(state.activeBrush));const draft={...source,parentHash:source.parentHash||parent};root.innerHTML=`<section class="section"><div class="field"><label>画笔名字</label><input id="edit-name" type="text" maxlength="16" value="${esc(source.name)}"></div><div class="field"><label>笔尖</label><select id="edit-kind">${KIND_ORDER.map(k=>`<option value="${k}" ${source.kind===k?"selected":""}>${KIND_NAMES[k]}</option>`).join("")}</select></div><div class="control"><label>颜色</label><input id="edit-color" type="color" value="${source.color}"><output id="edit-color-out">${source.color.toUpperCase()}</output></div><div class="control"><label>粗细</label><input id="edit-size" type="range" min="2" max="64" value="${source.size}"><output id="edit-size-out">${Math.round(source.size)}</output></div><div class="control"><label>透明度</label><input id="edit-opacity" type="range" min="5" max="100" value="${Math.round(source.opacity*100)}"><output id="edit-opacity-out">${Math.round(source.opacity*100)}%</output></div><div class="control"><label>间距</label><input id="edit-spacing" type="range" min="6" max="100" value="${source.spacing}"><output id="edit-spacing-out">${Math.round(source.spacing)}</output></div><div class="control"><label>随机感</label><input id="edit-jitter" type="range" min="0" max="100" value="${Math.round(source.jitter*100)}"><output id="edit-jitter-out">${Math.round(source.jitter*100)}%</output></div><div class="seed-box"><small>实时种子</small><code id="edit-seed"></code></div></section><div class="sheet-actions"><button class="secondary" id="copy-edit-seed">复制种子</button><button class="primary" id="save-edit-brush">保存画笔</button></div>`;const sync=()=>{draft.name=$("#edit-name",root).value.trim()||`我的${KIND_NAMES[draft.kind]}笔`;draft.kind=$("#edit-kind",root).value;draft.color=$("#edit-color",root).value;draft.size=Number($("#edit-size",root).value);draft.opacity=Number($("#edit-opacity",root).value)/100;draft.spacing=Number($("#edit-spacing",root).value);draft.jitter=Number($("#edit-jitter",root).value)/100;$("#edit-color-out",root).textContent=draft.color.toUpperCase();$("#edit-size-out",root).textContent=draft.size;$("#edit-opacity-out",root).textContent=`${Math.round(draft.opacity*100)}%`;$("#edit-spacing-out",root).textContent=draft.spacing;$("#edit-jitter-out",root).textContent=`${Math.round(draft.jitter*100)}%`;$("#edit-seed",root).textContent=encodeBrush(draft);state.activeBrush=cloneBrush(draft);updateUI()};$$('input,select',root).forEach(el=>el.oninput=sync);sync();$("#copy-edit-seed",root).onclick=()=>shareBrush(draft);$("#save-edit-brush",root).onclick=()=>saveCustomBrush(draft)}
function renderImport(root){root.innerHTML=`<section class="section"><div class="field"><label>WB2 画笔种子</label><input class="seed-input" id="brush-seed-input" type="text" maxlength="80" placeholder="WB2-…" autocomplete="off" spellcheck="false"></div><div id="seed-preview" class="seed-box" hidden></div><button class="primary wide-btn" id="decode-brush">识别画笔</button></section>`;$("#decode-brush",root).onclick=()=>{const box=$("#seed-preview",root);try{const code=$("#brush-seed-input",root).value,b=decodeBrush(code),fp=fingerprint(code);box.hidden=false;box.innerHTML=`<strong>收到一支 ${KIND_NAMES[b.kind]}画笔</strong><p class="tip">${b.color.toUpperCase()} · 粗细 ${Math.round(b.size)} · 指纹 ${fp}</p><div class="sheet-actions"><button class="secondary" id="use-seed-brush">立即试笔</button><button class="primary" id="save-seed-brush">收入画笔盒</button></div>`;$("#use-seed-brush",box).onclick=()=>{setActiveBrush({...b,name:`共享${KIND_NAMES[b.kind]}笔`});closeSheet();toast("收到一支新画笔")};$("#save-seed-brush",box).onclick=()=>{b.parentHash=fnv(code);saveCustomBrush({...b,name:`共享${KIND_NAMES[b.kind]}笔`},code)}}catch(e){box.hidden=false;box.textContent=e.message}}}
function saveCustomBrush(input,seedOverride){const b=cloneBrush(input),name=String(input.name||`我的${KIND_NAMES[b.kind]}笔`).slice(0,16),seed=seedOverride||encodeBrush(b);if(!state.customBrushes.some(x=>x.seed===seed))state.customBrushes.push({name,seed,brush:b});else{const x=state.customBrushes.find(x=>x.seed===seed);x.name=name;x.brush=b}state.activeBrush={...b,name};saveProject();updateUI();toast("画笔已收入画笔盒");closeSheet()}
async function shareBrush(input){const b=cloneBrush(input),seed=encodeBrush(b),name=input.name||b.name||`我的${KIND_NAMES[b.kind]}笔`,text=`我在《纹生万象》调了一支「${name}」。\n复制画笔种子即可带走：\n${seed}`;await copyText(text);toast(`画笔种子已复制 · ${fingerprint(seed)}`)}

function esc(text){return String(text??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{const ta=document.createElement("textarea");ta.value=text;ta.style.position="fixed";ta.style.opacity="0";document.body.appendChild(ta);ta.select();const ok=document.execCommand("copy");ta.remove();return ok}}

function renderBackground(ctx,w,h){ctx.fillStyle=state.background.color;ctx.fillRect(0,0,w,h);if(state.background.id!=="ink"){const rand=rng(9527);ctx.fillStyle="rgba(71,54,42,.035)";const count=Math.min(900,Math.round(w*h/4300));for(let i=0;i<count;i++){ctx.fillRect(rand()*w,rand()*h,Math.max(1,w/1600),Math.max(1,w/1600))}}}
async function exportArtwork(width,share){if(state.exporting)return;state.exporting=true;toast("正在高清成图…");await new Promise(requestAnimationFrame);const height=Math.round(width/0.75),out=document.createElement("canvas");out.width=width;out.height=height;const x=out.getContext("2d",{alpha:false});renderBackground(x,width,height);for(const s of state.strokes)renderStroke(x,s,width,height);const blob=await new Promise(r=>out.toBlob(r,"image/png",1));if(!blob){state.exporting=false;toast("生成失败，请重试");return}const name=`纹生万象-${Date.now()}.png`,file=new File([blob],name,{type:"image/png"});try{if(share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:"纹生万象 · 国风随笔画",text:"我用国风画笔画了一张随笔画。"});toast("已打开系统分享")}else{const xhs=window.xhs?.miniTool;if(!share&&typeof xhs?.saveImage==="function"){await xhs.saveImage(out.toDataURL("image/png"));toast("高清作品已保存")}else{const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);toast(`${width} × ${height} PNG 已生成`)}}}catch(e){console.warn(e);const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);toast("已生成高清 PNG")}out.width=out.height=1;state.exporting=false}

$("#undo").onclick=undo;$("#redo").onclick=redo;$("#fit-view").onclick=()=>resetView();$("#open-brushes").onclick=()=>{setMode("draw");openSheet("brush")};$("#open-size").onclick=()=>openSheet("size");$("#open-more").onclick=()=>openSheet("more");$("#open-export").onclick=()=>openSheet("export");$("#eraser").onclick=()=>setMode(state.mode==="erase"?"draw":"erase");$("#quick-color").oninput=e=>{state.activeBrush.color=e.target.value;state.activeBrush.name=`自调${KIND_NAMES[state.activeBrush.kind]}笔`;state.mode="draw";updateUI();scheduleSave()};$("#close-info").onclick=()=>$("#info-dialog").close();
window.addEventListener("resize",()=>{clearTimeout(window.__wswResize);window.__wswResize=setTimeout(setCanvasSizeFromResize,120)});
window.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redo()}});

function benchmark(){const sample={id:"bench",seed:123,brush:cloneBrush(PRESETS[0]),points:Array.from({length:100},(_,i)=>({x:.1+.8*i/99,y:.5+Math.sin(i/12)*.2,p:.7}))};const c=document.createElement("canvas");c.width=720;c.height=960;const x=c.getContext("2d"),times=[];for(let i=0;i<30;i++){const t=performance.now();renderStroke(x,sample,720,960);times.push(performance.now()-t);x.clearRect(0,0,720,960)}return{avg:times.reduce((a,b)=>a+b,0)/times.length,max:Math.max(...times)}}
function init(){loadProject();setPaperBackground();fitPaper();renderCommitted();updateUI();applyView()}
window.WenShengWanXiang={state,encodeBrush,decodeBrush,fingerprint,benchmark,exportArtwork,resetView};
init();
})();
