(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const TYPES={S:1,M:2,R:3,P:4,C:5,H:6},TYPE_CHARS={1:"S",2:"M",3:"R",4:"P",5:"C",6:"H"};
const LAYOUTS=["along","mirror","horizontal","vertical","tile","ring"],SYMMETRIES=["none","lr","tb","quad"],ROTATIONS=["none","soft","tilt","follow","alternate"],STAGGERS=["none","half","flip","alternate"],SCALES=["uniform","grow","shrink","breathe"];
const LABEL={layout:{along:"沿势",mirror:"镜生",horizontal:"横生",vertical:"纵生",tile:"四方",ring:"环生"},symmetry:{none:"无",lr:"左右",tb:"上下",quad:"四向"},rotation:{none:"不转",soft:"微旋",tilt:"斜转",follow:"随势",alternate:"交替"},stagger:{none:"整齐",half:"错半格",flip:"隔格翻转",alternate:"大小交替"},scale:{uniform:"均匀",grow:"渐大",shrink:"渐小",breathe:"呼吸"}};
const BUILTIN_MOTIFS=[{id:"yunlei",name:"云雷",desc:"回旋几何"},{id:"vine",name:"缠枝",desc:"枝蔓相接"},{id:"petal",name:"莲瓣",desc:"瓣瓣相生"},{id:"rosette",name:"团花",desc:"中心放射"},{id:"ruyi",name:"如意",desc:"云气回环"}];
const BUILTIN_RULES=[
{id:"mirror",name:"镜生",rule:{layout:"mirror",symmetry:"lr",repeat:7,rotation:"follow",stagger:"none",scale:"uniform"}},
{id:"flow",name:"回风",rule:{layout:"along",symmetry:"none",repeat:9,rotation:"follow",stagger:"alternate",scale:"breathe"}},
{id:"band",name:"横生",rule:{layout:"horizontal",symmetry:"none",repeat:8,rotation:"alternate",stagger:"half",scale:"uniform"}},
{id:"tile",name:"四方",rule:{layout:"tile",symmetry:"quad",repeat:6,rotation:"alternate",stagger:"half",scale:"uniform"}},
{id:"ring",name:"团华",rule:{layout:"ring",symmetry:"none",repeat:10,rotation:"follow",stagger:"none",scale:"breathe"}}
];
const BUILTIN_PALETTES=[
{id:"cinnabar",name:"朱砂",colors:["#f4ead9","#a34635","#385a57","#bd8b4d"]},
{id:"lapis",name:"石青",colors:["#edf0e8","#315f72","#a34c3b","#c39a58"]},
{id:"daiqing",name:"黛青",colors:["#f0eee4","#3f625b","#a24e3f","#b98a4e"]},
{id:"ink",name:"松烟",colors:["#e9e1d5","#293230","#a5483d","#b89154"]},
{id:"moon",name:"月白",colors:["#f1f5ef","#527b78","#a7443a","#c59b5e"]}
];
const DEMOS=[t=>({x:.14+t*.72,y:.62-Math.sin(t*Math.PI)*.28}),t=>({x:.12+t*.76,y:.5+Math.sin(t*Math.PI*2)*.12}),t=>({x:.16+t*.68,y:.32+t*.32+Math.sin(t*Math.PI*2)*.06}),t=>{const a=t*Math.PI*1.7,r=.06+t*.3;return{x:.5+Math.cos(a)*r,y:.5+Math.sin(a)*r}},t=>({x:.14+t*.72,y:.65-(t<.5?t*1.05:(1-t)*1.05)}),t=>({x:.12+t*.76,y:.55+Math.sin(t*Math.PI*4)*(.03+.08*t)})];
const DEFAULT_STROKE=Array.from({length:16},(_,i)=>{const t=i/15;return{x:.15+t*.7,y:.62-Math.sin(t*Math.PI)*.25}});
const defaultRule=()=>({...BUILTIN_RULES[0].rule});
const defaultPalette=()=>({id:"cinnabar",name:"朱砂",colors:[...BUILTIN_PALETTES[0].colors],custom:false});
const state={view:"create",mode:"EMPTY",stroke:[],raw:[],motif:{kind:"builtin",id:"yunlei",name:"云雷"},rule:defaultRule(),ruleName:"镜生",palette:defaultPalette(),parent:0,code:"",fingerprint:"-----",components:[],atlas:[],cache:{strokeKey:"",model:null,planKey:"",plan:null},drawing:false,lastPoint:null,renderFrame:0,toastTimer:0};
const canvas=$("#stage-canvas"),ctx=canvas.getContext("2d",{alpha:false});

function hashBytes(bytes){let h=0x811c9dc5;for(const b of bytes){h^=b;h=Math.imul(h,0x01000193)}return h>>>0}
function hashString(s){let h=0x811c9dc5;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,0x01000193)}return h>>>0}
function fpText(v){const abc="ABCDEFGHJKMNPQRSTVWXYZ23456789";let n=v>>>0,out="";for(let i=0;i<5;i++){out+=abc[n&31];n>>>=5}return out}
function crc16(bytes){let crc=0xffff;for(const b of bytes){crc^=b<<8;for(let i=0;i<8;i++)crc=(crc&0x8000)?((crc<<1)^0x1021)&0xffff:(crc<<1)&0xffff}return crc}
function b64url(bytes){let s="";for(let i=0;i<bytes.length;i+=0x4000)s+=String.fromCharCode(...bytes.slice(i,i+0x4000));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function unb64url(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
class Writer{constructor(){this.a=[]}b(v){this.a.push(v&255)}u32(v){this.b(v>>>24);this.b(v>>>16);this.b(v>>>8);this.b(v)}bytes(arr){for(const v of arr)this.b(v)}finish(){return this.a}}
class Reader{constructor(a){this.a=a;this.i=0}b(){if(this.i>=this.a.length)throw Error("truncated");return this.a[this.i++]}u32(){return((this.b()<<24)|(this.b()<<16)|(this.b()<<8)|this.b())>>>0}left(){return this.a.length-this.i}}
function quantizePoints(points,max=16){if(!points?.length)return DEFAULT_STROKE.map(p=>({...p}));const src=points.length<=max?points:Array.from({length:max},(_,i)=>points[Math.round(i*(points.length-1)/(max-1))]);return src.map(p=>({x:clamp(p.x,0,1),y:clamp(p.y,0,1)}))}
function writePoints(w,points,max=16){const ps=quantizePoints(points,max);w.b(ps.length);for(const p of ps){w.b(Math.round(p.x*31));w.b(Math.round(p.y*31))}}
function readPoints(r,max=24){const n=r.b();if(!n||n>max)throw Error("bad points");const ps=[];for(let i=0;i<n;i++)ps.push({x:r.b()/31,y:r.b()/31});return ps}
function motifPayload(m){const w=new Writer;if(m.kind==="builtin"){w.b(0);w.b(Math.max(0,BUILTIN_MOTIFS.findIndex(x=>x.id===m.id)))}else{w.b(1);const strokes=(m.strokes||[]).slice(0,2);w.b(strokes.length||1);for(const s of (strokes.length?strokes:[DEFAULT_STROKE]))writePoints(w,s,24)}return w.finish()}
function readMotif(r){const kind=r.b();if(kind===0){const m=BUILTIN_MOTIFS[r.b()]||BUILTIN_MOTIFS[0];return{kind:"builtin",id:m.id,name:m.name}}if(kind!==1)throw Error("bad motif");const n=clamp(r.b(),1,2),strokes=[];for(let i=0;i<n;i++)strokes.push(readPoints(r,24));return{kind:"custom",name:"自造纹元",strokes}}
function rulePayload(rule){return[LAYOUTS.indexOf(rule.layout),SYMMETRIES.indexOf(rule.symmetry),clamp(rule.repeat||6,2,12),ROTATIONS.indexOf(rule.rotation),STAGGERS.indexOf(rule.stagger),SCALES.indexOf(rule.scale)].map(v=>Math.max(0,v))}
function readRule(r){return{layout:LAYOUTS[r.b()]||"mirror",symmetry:SYMMETRIES[r.b()]||"none",repeat:clamp(r.b(),2,12),rotation:ROTATIONS[r.b()]||"follow",stagger:STAGGERS[r.b()]||"none",scale:SCALES[r.b()]||"uniform"}}
function hex12(hex){const h=hex.replace("#","");const n=h.length===3?h:h[0]+h[2]+h[4];return parseInt(n,16)&4095}
function expand12(n){const s=n.toString(16).padStart(3,"0");return`#${s[0]}${s[0]}${s[1]}${s[1]}${s[2]}${s[2]}`}
function palettePayload(p){const out=[];for(const c of p.colors.slice(0,4)){const n=hex12(c);out.push(n>>8,n&255)}return out}
function readPalette(r){const colors=[];for(let i=0;i<4;i++)colors.push(expand12((r.b()<<8)|r.b()));return{id:"custom",name:"自造色谱",colors,custom:true}}
function encodeObject(type,obj){const w=new Writer;if(type===TYPES.S)writePoints(w,obj.stroke||obj,16);if(type===TYPES.M)w.bytes(motifPayload(obj.motif||obj));if(type===TYPES.R)w.bytes(rulePayload(obj.rule||obj));if(type===TYPES.P)w.bytes(palettePayload(obj.palette||obj));if(type===TYPES.C||type===TYPES.H){writePoints(w,obj.stroke,16);const mp=motifPayload(obj.motif);w.b(mp.length);w.bytes(mp);w.bytes(rulePayload(obj.rule));w.bytes(palettePayload(obj.palette));w.u32(obj.parent||0);if(type===TYPES.H)w.b(obj.lockMask||0)}const body=w.finish(),crc=crc16(body),all=[...body,crc>>8,crc&255];return`WX2-${TYPE_CHARS[type]}-${b64url(all)}`}
function decodeObject(code){const s=String(code||"").trim();if(s.startsWith("WW-"))return decodeLegacy(s);const m=/^WX2-([SMRPCH])-([A-Za-z0-9_-]{3,170})$/.exec(s);if(!m)throw Error("格式不正确");const type=TYPES[m[1]],all=[...unb64url(m[2])];if(all.length<3||all.length>150)throw Error("长度不正确");const body=all.slice(0,-2),got=(all.at(-2)<<8)|all.at(-1);if(crc16(body)!==got)throw Error("校验失败");const r=new Reader(body),out={type};if(type===TYPES.S)out.stroke=readPoints(r,16);if(type===TYPES.M)out.motif=readMotif(r);if(type===TYPES.R)out.rule=readRule(r);if(type===TYPES.P)out.palette=readPalette(r);if(type===TYPES.C||type===TYPES.H){out.stroke=readPoints(r,16);const ml=r.b();if(ml>70||ml>r.left())throw Error("纹元数据损坏");const mr=new Reader(body.slice(r.i,r.i+ml));out.motif=readMotif(mr);r.i+=ml;out.rule=readRule(r);out.palette=readPalette(r);out.parent=r.u32();if(type===TYPES.H)out.lockMask=r.b()}if(r.left()!==0)throw Error("多余数据");out.hash=hashBytes(body);out.fingerprint=fpText(out.hash);out.code=s;return out}
const LEGACY_ALPHABET="ABCDEFGHJKMNPQRSTVWXYZ23456789LU";
function legacyNum(s){let n=0;for(let i=s.length-1;i>=0;i--)n=n*32+LEGACY_ALPHABET.indexOf(s[i]);return n>>>0}
function decodeLegacy(seed){const n=seed.trim().toUpperCase(),body=n.slice(3,-2);if(body.length<5)throw Error("旧 Seed 损坏");const meta=legacyNum(body.slice(0,4)),count=LEGACY_ALPHABET.indexOf(body[4]);if(count<1||count>11||body.length!==5+count*2)throw Error("旧 Seed 损坏");const systems=["yunlei","vine","petal","rosette","ruyi"],struct=["mirror","ring","horizontal","tile","ring"],pal=["cinnabar","lapis","daiqing","ink","moon"],stroke=[];for(let i=0;i<count;i++)stroke.push({x:LEGACY_ALPHABET.indexOf(body[5+i*2])/31,y:LEGACY_ALPHABET.indexOf(body[6+i*2])/31});const mi=(meta>>>3)&7,ri=(meta>>>6)&7,pi=(meta>>>9)&7,m=BUILTIN_MOTIFS.find(x=>x.id===systems[mi])||BUILTIN_MOTIFS[0],bp=BUILTIN_PALETTES.find(x=>x.id===pal[pi])||BUILTIN_PALETTES[0];const obj={type:TYPES.C,stroke,motif:{kind:"builtin",id:m.id,name:m.name},rule:{...defaultRule(),layout:struct[ri]||"mirror"},palette:{id:bp.id,name:bp.name,colors:[...bp.colors],custom:false},parent:0};obj.code=encodeObject(TYPES.C,obj);obj.hash=hashString(obj.code);obj.fingerprint=fpText(obj.hash);obj.legacy=true;return obj}
function currentObj(){return{stroke:quantizePoints(state.stroke,16),motif:state.motif,rule:state.rule,palette:state.palette,parent:state.parent}}
function updateCode(){if(!state.stroke.length)return;state.code=encodeObject(TYPES.C,currentObj());const o=decodeObject(state.code);state.fingerprint=o.fingerprint;$("#fingerprint").textContent=state.fingerprint;syncMeta()}

function smooth(points,it=2){let a=points.map(p=>({...p}));for(let k=0;k<it;k++){if(a.length<3)break;const b=[a[0]];for(let i=0;i<a.length-1;i++){const p=a[i],q=a[i+1];b.push({x:p.x*.75+q.x*.25,y:p.y*.75+q.y*.25},{x:p.x*.25+q.x*.75,y:p.y*.25+q.y*.75})}b.push(a.at(-1));a=b}return a}
function resample(points,count=64){const src=smooth(points.length>1?points:DEFAULT_STROKE,2),lens=[0];for(let i=1;i<src.length;i++)lens.push(lens.at(-1)+Math.hypot(src[i].x-src[i-1].x,src[i].y-src[i-1].y));const total=Math.max(.001,lens.at(-1)),out=[];let j=0;for(let i=0;i<count;i++){const target=total*i/(count-1);while(j<lens.length-2&&lens[j+1]<target)j++;const seg=Math.max(.00001,lens[j+1]-lens[j]),t=clamp((target-lens[j])/seg,0,1),a=src[j],b=src[j+1];out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,s:i/(count-1)})}for(let i=0;i<out.length;i++){const a=out[Math.max(0,i-1)],b=out[Math.min(out.length-1,i+1)],dx=b.x-a.x,dy=b.y-a.y,l=Math.max(.0001,Math.hypot(dx,dy));out[i].angle=Math.atan2(dy,dx);out[i].nx=-dy/l;out[i].ny=dx/l}return out}
function strokeKey(){return quantizePoints(state.stroke,16).map(p=>`${Math.round(p.x*31)},${Math.round(p.y*31)}`).join(";")}
function compileStroke(){const key=strokeKey();if(state.cache.strokeKey===key&&state.cache.model)return state.cache.model;const model=resample(quantizePoints(state.stroke,16),64);state.cache.strokeKey=key;state.cache.model=model;state.cache.planKey="";return model}
function ruleKey(){return[state.cache.strokeKey,state.motif.kind,state.motif.id||JSON.stringify(state.motif.strokes),...rulePayload(state.rule)].join("|")}
function scaleAt(mode,t){if(mode==="grow")return .72+t*.5;if(mode==="shrink")return 1.2-t*.45;if(mode==="breathe")return .86+Math.sin(t*Math.PI*2)*.2;return 1}
function compilePlan(w=canvas.width,h=canvas.height){const model=compileStroke(),key=`${ruleKey()}@${w}x${h}`;if(state.cache.planKey===key&&state.cache.plan)return state.cache.plan;const r=state.rule,ins=[],base=Math.min(w,h),marginX=w*.13,marginY=h*.18,iw=w*.74,ih=h*.64;const put=(x,y,rot,scale=1,flip=1,t=0)=>ins.push({x,y,rot,scale,flip,t});const pointAt=t=>model[Math.round(clamp(t,0,1)*(model.length-1))];
if(r.layout==="along"||r.layout==="mirror"){const n=clamp(r.repeat,2,12);for(let i=0;i<n;i++){const t=(i+.5)/n,p=pointAt(t),x=marginX+p.x*iw,y=marginY+p.y*ih,rot=r.rotation==="follow"?p.angle:(r.rotation==="tilt"?.55:r.rotation==="soft"?.18:r.rotation==="alternate"?(i%2?.45:-.45):0),sc=scaleAt(r.scale,t)*(r.stagger==="alternate"&&i%2?.76:1);put(x,y,rot,sc,r.stagger==="flip"&&i%2?-1:1,t);if(r.layout==="mirror")put(x,h-y,-rot,sc,-1,t+.01)}}
if(r.layout==="horizontal"){const rows=r.symmetry==="quad"?4:3,n=clamp(r.repeat,2,12);for(let row=0;row<rows;row++)for(let i=0;i<n;i++){const off=r.stagger==="half"&&row%2?.5:0,t=(i+off+.5)/n,x=(t%1)*w,y=h*(.25+row*(.5/Math.max(1,rows-1))),rot=r.rotation==="alternate"?(i%2?.4:-.4):0;put(x,y,rot,scaleAt(r.scale,i/n),r.stagger==="flip"&&i%2?-1:1,(row*n+i)/(rows*n))}}
if(r.layout==="vertical"){const cols=3,n=clamp(r.repeat,2,12);for(let col=0;col<cols;col++)for(let i=0;i<n;i++){const off=r.stagger==="half"&&col%2?.5:0,t=(i+off+.5)/n,x=w*(.25+col*.25),y=(t%1)*h,rot=Math.PI/2+(r.rotation==="alternate"?(i%2?.35:-.35):0);put(x,y,rot,scaleAt(r.scale,i/n),1,(col*n+i)/(cols*n))}}
if(r.layout==="tile"){const n=clamp(Math.round(r.repeat/2)+2,3,7),cellW=w/n,cellH=h/n;for(let y=0;y<n;y++)for(let x=0;x<n;x++){const ox=r.stagger==="half"&&y%2?cellW*.5:0,t=(y*n+x)/(n*n);put((x+.5)*cellW+ox,(y+.5)*cellH,r.rotation==="alternate"?((x+y)%2?.4:-.4):0,scaleAt(r.scale,t)*.82,r.stagger==="flip"&&(x+y)%2?-1:1,t)}}
if(r.layout==="ring"){const n=clamp(r.repeat,4,12),cx=w/2,cy=h/2,rad=base*.31;for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/n,t=i/n;put(cx+Math.cos(a)*rad,cy+Math.sin(a)*rad,r.rotation==="none"?0:a+Math.PI/2,scaleAt(r.scale,t),r.stagger==="flip"&&i%2?-1:1,t)}}
const expandSym=(items)=>{if(r.symmetry==="none"||r.layout==="mirror")return items;const out=[...items];for(const q of items){if(r.symmetry==="lr"||r.symmetry==="quad")out.push({...q,x:w-q.x,rot:-q.rot,flip:-q.flip,t:q.t+.002});if(r.symmetry==="tb"||r.symmetry==="quad")out.push({...q,y:h-q.y,rot:-q.rot,t:q.t+.003})}return out};const plan=expandSym(ins).sort((a,b)=>a.t-b.t);state.cache.planKey=key;state.cache.plan=plan;return plan}
function colorMix(hex,amount){const h=hex.slice(1),n=parseInt(h,16),r=clamp((n>>16)+amount,0,255),g=clamp(((n>>8)&255)+amount,0,255),b=clamp((n&255)+amount,0,255);return`rgb(${r},${g},${b})`}
function paper(c,w,h,p,exporting=false){const [paper,primary,secondary,accent]=p.colors;c.fillStyle=paper;c.fillRect(0,0,w,h);const g=c.createRadialGradient(w*.52,h*.4,10,w*.52,h*.4,Math.max(w,h)*.7);g.addColorStop(0,"rgba(255,255,255,.48)");g.addColorStop(1,"rgba(255,255,255,0)");c.fillStyle=g;c.fillRect(0,0,w,h);if(exporting){const rnd=seeded(hashString(state.code||"paper"));c.fillStyle="rgba(60,45,35,.045)";for(let i=0;i<Math.min(320,Math.round(w*h/6000));i++)c.fillRect(rnd()*w,rnd()*h,1+rnd()*1.4,1+rnd()*1.4)}c.strokeStyle=primary;c.globalAlpha=.18;c.lineWidth=Math.max(1,w*.0015);c.strokeRect(w*.055,h*.04,w*.89,h*.92);c.globalAlpha=1}
function seeded(seed){let a=seed||1;return()=>{a|=0;a=(a+0x6d2b79f5)|0;let t=Math.imul(a^(a>>>15),1|a);t^=t+Math.imul(t^(t>>>7),61|t);return((t^(t>>>14))>>>0)/4294967296}}
function drawBuiltin(c,id,size,colors){const [paper,primary,secondary,accent]=colors;c.lineJoin="round";c.lineCap="round";c.lineWidth=Math.max(1.2,size*.045);if(id==="yunlei"){c.strokeStyle=primary;c.beginPath();c.moveTo(-size*.5,size*.38);c.lineTo(-size*.5,-size*.4);c.lineTo(size*.48,-size*.4);c.lineTo(size*.48,size*.34);c.lineTo(-size*.22,size*.34);c.lineTo(-size*.22,-size*.12);c.lineTo(size*.2,-size*.12);c.lineTo(size*.2,size*.12);c.lineTo(0,size*.12);c.stroke();c.fillStyle=accent;c.fillRect(-size*.045,size*.04,size*.09,size*.09)}else if(id==="petal"){for(let i=0;i<6;i++){c.save();c.rotate((i-2.5)*.32);c.fillStyle=i%2?colorMix(primary,35):paper;c.strokeStyle=primary;c.beginPath();c.moveTo(0,size*.35);c.bezierCurveTo(size*.4,size*.08,size*.34,-size*.42,0,-size*.55);c.bezierCurveTo(-size*.34,-size*.42,-size*.4,size*.08,0,size*.35);c.fill();c.stroke();c.restore()}c.fillStyle=accent;c.beginPath();c.arc(0,size*.16,size*.08,0,Math.PI*2);c.fill()}else if(id==="rosette"){for(let i=0;i<8;i++){c.save();c.rotate(i*Math.PI/4);c.fillStyle=i%2?secondary:primary;c.globalAlpha=.78;c.beginPath();c.ellipse(0,-size*.28,size*.13,size*.32,0,0,Math.PI*2);c.fill();c.restore()}c.globalAlpha=1;c.fillStyle=accent;c.beginPath();c.arc(0,0,size*.12,0,Math.PI*2);c.fill()}else if(id==="vine"){c.strokeStyle=secondary;c.lineWidth=size*.05;c.beginPath();c.moveTo(-size*.55,size*.15);c.bezierCurveTo(-size*.25,-size*.48,size*.15,size*.48,size*.55,-size*.12);c.stroke();c.fillStyle=primary;for(const [x,y,a]of[[-.28,-.1,-.8],[.18,.11,.8]]){c.save();c.translate(x*size,y*size);c.rotate(a);c.beginPath();c.ellipse(0,-size*.15,size*.09,size*.22,0,0,Math.PI*2);c.fill();c.restore()}c.fillStyle=accent;c.beginPath();c.arc(size*.02,-size*.18,size*.11,0,Math.PI*2);c.fill()}else{c.fillStyle=colorMix(paper,-8);c.strokeStyle=primary;c.beginPath();c.moveTo(-size*.48,size*.14);c.bezierCurveTo(-size*.65,-size*.22,-size*.34,-size*.43,-size*.12,-size*.24);c.bezierCurveTo(0,-size*.6,size*.42,-size*.5,size*.38,-size*.18);c.bezierCurveTo(size*.65,-size*.24,size*.63,size*.2,size*.42,size*.28);c.bezierCurveTo(size*.2,size*.4,-size*.05,size*.24,-size*.12,size*.1);c.bezierCurveTo(-size*.25,size*.35,-size*.44,size*.34,-size*.48,size*.14);c.closePath();c.fill();c.stroke();c.strokeStyle=secondary;c.beginPath();c.arc(-size*.05,size*.06,size*.16,-.5,Math.PI*1.5);c.stroke()}}
function customBounds(strokes){const all=strokes.flat();let minX=1,minY=1,maxX=0,maxY=0;for(const p of all){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)}return{minX,minY,maxX,maxY,w:Math.max(.05,maxX-minX),h:Math.max(.05,maxY-minY)}}
function drawCustom(c,motif,size,colors){const strokes=motif.strokes||[],b=customBounds(strokes);c.strokeStyle=colors[1];c.fillStyle=colorMix(colors[0],-6);c.lineWidth=Math.max(1.3,size*.045);c.lineCap="round";c.lineJoin="round";for(const s of strokes){if(s.length<2)continue;c.beginPath();s.forEach((p,i)=>{const x=((p.x-b.minX)/b.w-.5)*size,y=((p.y-b.minY)/b.h-.5)*size;i?c.lineTo(x,y):c.moveTo(x,y)});const first=s[0],last=s.at(-1),closed=Math.hypot(first.x-last.x,first.y-last.y)<.1;if(closed){c.closePath();c.globalAlpha=.28;c.fill();c.globalAlpha=1}c.stroke()}}
function drawMotif(c,motif,size,palette){motif.kind==="builtin"?drawBuiltin(c,motif.id,size,palette.colors):drawCustom(c,motif,size,palette.colors)}
function paint(target,stateLike=state,progress=1,exporting=false){const c=target.getContext("2d",{alpha:false}),w=target.width,h=target.height,saveState={motif:state.motif,rule:state.rule,palette:state.palette,stroke:state.stroke,cache:state.cache};if(stateLike!==state){state.motif=stateLike.motif;state.rule=stateLike.rule;state.palette=stateLike.palette;state.stroke=stateLike.stroke;state.cache={strokeKey:"",model:null,planKey:"",plan:null}}paper(c,w,h,state.palette,exporting);const plan=compilePlan(w,h),base=Math.min(w,h),count=Math.ceil(plan.length*clamp(progress,0,1));for(let i=0;i<count;i++){const q=plan[i];c.save();c.translate(q.x,q.y);c.rotate(q.rot);c.scale(q.flip*q.scale,q.scale);const size=base*(state.rule.layout==="tile"?.12:state.rule.layout==="ring"?.14:.13);drawMotif(c,state.motif,size,state.palette);c.restore()}if(exporting){c.save();c.fillStyle=state.palette.colors[1];c.globalAlpha=.62;c.font=`600 ${Math.max(13,w*.018)}px "KaiTi",serif`;c.fillText("纹生万象",w*.075,h*.93);c.textAlign="right";c.font=`${Math.max(10,w*.013)}px system-ui`;c.fillText(`纹脉 ${state.fingerprint||fpText(hashString(state.code||""))}`,w*.925,h*.93);c.restore()}if(stateLike!==saveState){state.motif=saveState.motif;state.rule=saveState.rule;state.palette=saveState.palette;state.stroke=saveState.stroke;state.cache=saveState.cache}}
function render(progress=1){if(!state.stroke.length){drawBlank();return}paint(canvas,state,progress,false)}
function schedule(){if(state.renderFrame)return;state.renderFrame=requestAnimationFrame(()=>{state.renderFrame=0;render(1)})}
function drawBlank(){paper(ctx,canvas.width,canvas.height,state.palette,false)}
function animateGrowth(){state.mode="GENERATING";updateCode();const reduced=matchMedia("(prefers-reduced-motion:reduce)").matches,start=performance.now(),dur=reduced?80:560;showGrowth("一笔成纹");const frame=now=>{const t=clamp((now-start)/dur,0,1),e=1-Math.pow(1-t,3);render(e);if(t<1)requestAnimationFrame(frame);else{state.mode="READY";revealResult();showGrowth("你的第一纹已生长",700)}};requestAnimationFrame(frame)}
function showGrowth(text,hold=0){const el=$("#growth-word");el.textContent=text;el.classList.add("show");clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove("show"),hold||900)}

function canvasPoint(e,el=canvas){const r=el.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width,0,1),y:clamp((e.clientY-r.top)/r.height,0,1)}}
function pointerDown(e){if(state.view!=="create"||state.mode==="EXPORTING")return;e.preventDefault();canvas.setPointerCapture?.(e.pointerId);state.drawing=true;state.mode="DRAWING";state.raw=[];state.stroke=[];state.lastPoint=canvasPoint(e);state.raw.push(state.lastPoint);$("#draw-prompt").classList.add("hidden");drawBlank();drawInk(state.raw)}
function pointerMove(e){if(!state.drawing)return;e.preventDefault();const p=canvasPoint(e),last=state.raw.at(-1);if(Math.hypot((p.x-last.x)*canvas.width,(p.y-last.y)*canvas.height)<2.2)return;state.raw.push(p);drawInk(state.raw)}
function pointerUp(){if(!state.drawing)return;state.drawing=false;let pts=state.raw;if(pts.length<2){const p=pts[0]||{x:.5,y:.5};pts=[{x:p.x-.035,y:p.y},{x:p.x+.035,y:p.y-.02},{x:p.x+.065,y:p.y+.01}]}state.stroke=quantizePoints(pts,16);state.parent=0;state.cache={strokeKey:"",model:null,planKey:"",plan:null};animateGrowth()}
function drawInk(points){drawBlank();ctx.save();ctx.strokeStyle=state.palette.colors[1];ctx.lineWidth=6;ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();points.forEach((p,i)=>{const x=p.x*canvas.width,y=p.y*canvas.height;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.restore()}
function demo(){const fn=DEMOS[Math.floor(Math.random()*DEMOS.length)];state.stroke=Array.from({length:16},(_,i)=>fn(i/15));state.parent=0;state.cache={strokeKey:"",model:null,planKey:"",plan:null};$("#draw-prompt").classList.add("hidden");animateGrowth()}
function redraw(){state.stroke=[];state.raw=[];state.code="";state.parent=0;state.mode="EMPTY";state.cache={strokeKey:"",model:null,planKey:"",plan:null};$("#draw-prompt").classList.remove("hidden");hideResult();drawBlank()}
function inspire(){if(!state.stroke.length){demo();return}const m=BUILTIN_MOTIFS[Math.floor(Math.random()*BUILTIN_MOTIFS.length)],r=BUILTIN_RULES[Math.floor(Math.random()*BUILTIN_RULES.length)],p=BUILTIN_PALETTES[Math.floor(Math.random()*BUILTIN_PALETTES.length)];state.motif={kind:"builtin",id:m.id,name:m.name};state.rule={...r.rule};state.ruleName=r.name;state.palette={id:p.id,name:p.name,colors:[...p.colors],custom:false};state.cache.planKey="";updateCode();syncMeta();schedule();showGrowth("灵光一现",450)}
function revealResult(){$("#result-meta").hidden=false;$("#quick-edit").hidden=false;$("#primary-actions").hidden=false;$("#demo-stroke").hidden=true;syncMeta()}
function hideResult(){$("#result-meta").hidden=true;$("#quick-edit").hidden=true;$("#primary-actions").hidden=true;$("#demo-stroke").hidden=false}
function motifName(){return state.motif.name||"自造纹元"}function paletteName(){return state.palette.name||"自造色谱"}
function syncMeta(){const name=`${motifName()} · ${state.ruleName||LABEL.layout[state.rule.layout]} · ${paletteName()}`;$("#result-name").textContent=name;$("#quick-motif").textContent=motifName();$("#quick-rule").textContent=state.ruleName||LABEL.layout[state.rule.layout];$("#quick-palette").textContent=paletteName();if(state.stroke.length)$("#fingerprint").textContent=state.fingerprint}

function loadStore(){try{state.components=JSON.parse(localStorage.getItem("wsw:v2:components")||"[]");state.atlas=JSON.parse(localStorage.getItem("wsw:v2:atlas")||"[]")}catch{state.components=[];state.atlas=[]}updateCounts()}
function saveStore(){localStorage.setItem("wsw:v2:components",JSON.stringify(state.components.slice(-400)));localStorage.setItem("wsw:v2:atlas",JSON.stringify(state.atlas.slice(-300)));updateCounts()}
function updateCounts(){for(const t of["stroke","motif","rule","palette"]){const map={stroke:"S",motif:"M",rule:"R",palette:"P"};const el=$(`#count-${t}`);if(el)el.textContent=`${state.components.filter(x=>x.kind===map[t]).length} 个`}$("#atlas-count").textContent=`${state.atlas.length} 幅作品`}
function saveComponent(kind,obj,name){const type=TYPES[kind],code=encodeObject(type,obj),decoded=decodeObject(code),item={kind:TYPE_CHARS[type],code,name:name||`未命名 · ${decoded.fingerprint}`,fp:decoded.fingerprint,createdAt:Date.now()};if(!state.components.some(x=>x.code===code))state.components.push(item);saveStore();renderComponents();toast(kind==="R"?"新法已成 · 已收入工坊":"已收入万象工坊");return item}
function favorite(){if(!state.code)updateCode();if(state.atlas.some(x=>x.code===state.code)){toast("这一纹已经在纹谱里");return}state.atlas.push({code:state.code,fp:state.fingerprint,name:$("#result-name").textContent,createdAt:Date.now()});saveStore();$("#favorite").textContent="♥ 已藏";navigator.vibrate?.(8);showGrowth("藏",350);renderAtlas()}
function applyDecoded(o,remix=true){if(o.type===TYPES.S)state.stroke=o.stroke;if(o.type===TYPES.M)state.motif=o.motif;if(o.type===TYPES.R){state.rule=o.rule;state.ruleName=`纹法 · ${o.fingerprint}`}if(o.type===TYPES.P){state.palette=o.palette;state.palette.name=`色谱 · ${o.fingerprint}`}if(o.type===TYPES.C||o.type===TYPES.H){state.stroke=o.stroke;state.motif=o.motif;state.rule=o.rule;state.ruleName=`纹法 · ${o.fingerprint}`;state.palette=o.palette;state.palette.name=`色谱 · ${o.fingerprint}`;state.parent=remix?o.hash:(o.parent||0)}state.cache={strokeKey:"",model:null,planKey:"",plan:null};if(state.stroke.length){updateCode();revealResult();switchView("create");$("#draw-prompt").classList.add("hidden");render(1);showGrowth(o.legacy?"旧版纹样已恢复":"接到一纹",650)}else schedule()}
function componentObj(type){if(type===TYPES.S)return{stroke:state.stroke};if(type===TYPES.M)return{motif:state.motif};if(type===TYPES.R)return{rule:state.rule};if(type===TYPES.P)return{palette:state.palette}}

function openSheet(kind){if(!state.stroke.length&&["motif","rule","palette","share"].includes(kind)){toast("先画一笔，马上就有东西可以改");return}const titles={motif:["MOTIF","选择纹元"],rule:["RULE","选择 / 创造纹法"],palette:["PALETTE","选择色谱"],share:["PASS THE PATTERN","传这一纹"]};$("#sheet-kicker").textContent=titles[kind][0];$("#sheet-title").textContent=titles[kind][1];const body=$("#sheet-body");if(kind==="motif")renderMotifSheet(body);if(kind==="rule")renderRuleSheet(body);if(kind==="palette")renderPaletteSheet(body);if(kind==="share")renderShareSheet(body);$("#sheet-backdrop").hidden=false;$("#bottom-sheet").classList.add("open");$("#bottom-sheet").setAttribute("aria-hidden","false")}
function closeSheet(){$("#bottom-sheet").classList.remove("open");$("#bottom-sheet").setAttribute("aria-hidden","true");setTimeout(()=>$("#sheet-backdrop").hidden=true,220)}
function renderMotifSheet(root){const saved=state.components.filter(x=>x.kind==="M");root.innerHTML=`<div class="sheet-section"><h4>经典纹元</h4><div class="option-grid">${BUILTIN_MOTIFS.map(m=>`<button class="option ${state.motif.kind==="builtin"&&state.motif.id===m.id?"active":""}" data-motif="${m.id}"><strong>${m.name}</strong><small>${m.desc}</small></button>`).join("")}</div></div><div class="sheet-section"><h4>我的纹元</h4><div class="library-list">${saved.length?saved.slice(-6).reverse().map(x=>`<button class="option" data-code="${x.code}"><strong>${escapeHtml(x.name)}</strong><small>${x.fp}</small></button>`).join(""):"<div class='empty'>还没有自造纹元</div>"}</div><button class="sheet-create" id="create-motif">＋ 造一个纹元</button></div>`;$$('[data-motif]',root).forEach(b=>b.onclick=()=>{const m=BUILTIN_MOTIFS.find(x=>x.id===b.dataset.motif);state.motif={kind:"builtin",id:m.id,name:m.name};state.cache.planKey="";updateCode();syncMeta();schedule();renderMotifSheet(root)});$$('[data-code]',root).forEach(b=>b.onclick=()=>{try{applyDecoded(decodeObject(b.dataset.code),false);renderMotifSheet(root)}catch{}});$("#create-motif",root).onclick=()=>renderMotifEditor(root)}
function renderMotifEditor(root){root.innerHTML=`<div class="motif-editor"><div><canvas id="motif-canvas" width="280" height="280"></canvas><p class="motif-caption">画 1～2 笔，程序会自动压缩</p></div><div><canvas id="motif-preview" width="280" height="280"></canvas><p class="motif-caption">重复后的实时预览</p></div></div><div class="sheet-footer"><button class="ghost" id="motif-clear">清空</button><button class="primary" id="motif-save">存为我的纹元</button></div>`;const mc=$("#motif-canvas",root),pc=$("#motif-preview",root),mctx=mc.getContext("2d"),pctx=pc.getContext("2d"),strokes=[];let cur=null;function base(){mctx.fillStyle="#f4ead9";mctx.fillRect(0,0,280,280);mctx.strokeStyle="#a34635";mctx.lineWidth=5;mctx.lineCap="round";for(const s of strokes){mctx.beginPath();s.forEach((p,i)=>i?mctx.lineTo(p.x*280,p.y*280):mctx.moveTo(p.x*280,p.y*280));mctx.stroke()}pctx.fillStyle="#f4ead9";pctx.fillRect(0,0,280,280);if(strokes.length){const mo={kind:"custom",strokes:strokes.map(s=>quantizePoints(s,24))};for(let y=0;y<3;y++)for(let x=0;x<3;x++){pctx.save();pctx.translate((x+.5)*93,(y+.5)*93);drawCustom(pctx,mo,70,state.palette.colors);pctx.restore()}}}function pt(e){const r=mc.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width,0,1),y:clamp((e.clientY-r.top)/r.height,0,1)}}mc.onpointerdown=e=>{if(strokes.length>=2)strokes.shift();cur=[pt(e)];strokes.push(cur);mc.setPointerCapture?.(e.pointerId);base()};mc.onpointermove=e=>{if(!cur)return;const p=pt(e),l=cur.at(-1);if(Math.hypot(p.x-l.x,p.y-l.y)>.01){cur.push(p);base()}};mc.onpointerup=()=>{cur=null;base()};$("#motif-clear",root).onclick=()=>{strokes.length=0;base()};$("#motif-save",root).onclick=()=>{if(!strokes.length){toast("先画一个纹元");return}const motif={kind:"custom",name:"自造纹元",strokes:strokes.map(s=>quantizePoints(s,24))};state.motif=motif;state.cache.planKey="";saveComponent("M",{motif});updateCode();syncMeta();schedule();closeSheet()};base()}
function renderRuleSheet(root,editor=false){if(!editor){const saved=state.components.filter(x=>x.kind==="R");root.innerHTML=`<div class="sheet-section"><h4>经典纹法</h4><div class="option-grid">${BUILTIN_RULES.map(r=>`<button class="option ${state.ruleName===r.name?"active":""}" data-rule="${r.id}"><strong>${r.name}</strong><small>${LABEL.layout[r.rule.layout]} · ${LABEL.rotation[r.rule.rotation]}</small></button>`).join("")}</div></div><div class="sheet-section"><h4>我的纹法</h4>${saved.length?`<div class="option-grid">${saved.slice(-6).reverse().map(x=>`<button class="option" data-code="${x.code}"><strong>${escapeHtml(x.name)}</strong><small>${x.fp}</small></button>`).join("")}</div>`:"<div class='empty'>还没有自造纹法</div>"}<button class="sheet-create" id="create-rule">＋ 造一种纹法</button></div>`;$$('[data-rule]',root).forEach(b=>b.onclick=()=>{const r=BUILTIN_RULES.find(x=>x.id===b.dataset.rule);state.rule={...r.rule};state.ruleName=r.name;state.cache.planKey="";updateCode();syncMeta();schedule();renderRuleSheet(root)});$$('[data-code]',root).forEach(b=>b.onclick=()=>{applyDecoded(decodeObject(b.dataset.code),false);renderRuleSheet(root)});$("#create-rule",root).onclick=()=>renderRuleEditor(root);return}}
function renderRuleEditor(root){const r={...state.rule};root.innerHTML=`<div class="sheet-section"><div class="rule-line"><label>排列</label><select data-r="layout">${LAYOUTS.map(v=>`<option value="${v}" ${r.layout===v?"selected":""}>${LABEL.layout[v]}</option>`).join("")}</select></div><div class="rule-line"><label>对称</label><select data-r="symmetry">${SYMMETRIES.map(v=>`<option value="${v}" ${r.symmetry===v?"selected":""}>${LABEL.symmetry[v]}</option>`).join("")}</select></div><div class="rule-line"><label>重复 <b id="repeat-out">${r.repeat}</b></label><input data-r="repeat" type="range" min="2" max="12" value="${r.repeat}"></div><div class="rule-line"><label>旋转</label><select data-r="rotation">${ROTATIONS.map(v=>`<option value="${v}" ${r.rotation===v?"selected":""}>${LABEL.rotation[v]}</option>`).join("")}</select></div><div class="rule-line"><label>交错</label><select data-r="stagger">${STAGGERS.map(v=>`<option value="${v}" ${r.stagger===v?"selected":""}>${LABEL.stagger[v]}</option>`).join("")}</select></div><div class="rule-line"><label>生长</label><select data-r="scale">${SCALES.map(v=>`<option value="${v}" ${r.scale===v?"selected":""}>${LABEL.scale[v]}</option>`).join("")}</select></div></div><button class="sheet-create" id="rule-random">✦ 灵光一现</button><div class="sheet-footer"><button class="ghost" id="rule-cancel">返回</button><button class="primary" id="rule-save">存为我的纹法</button></div>`;const sync=()=>{state.rule={...r};state.ruleName="自造纹法";state.cache.planKey="";updateCode();syncMeta();schedule()};$$('[data-r]',root).forEach(el=>el.oninput=()=>{r[el.dataset.r]=el.dataset.r==="repeat"?Number(el.value):el.value;if(el.dataset.r==="repeat")$("#repeat-out",root).textContent=el.value;sync()});$("#rule-random",root).onclick=()=>{r.layout=LAYOUTS[Math.floor(Math.random()*LAYOUTS.length)];r.symmetry=SYMMETRIES[Math.floor(Math.random()*SYMMETRIES.length)];r.repeat=4+Math.floor(Math.random()*8);r.rotation=ROTATIONS[Math.floor(Math.random()*ROTATIONS.length)];r.stagger=STAGGERS[Math.floor(Math.random()*STAGGERS.length)];r.scale=SCALES[Math.floor(Math.random()*SCALES.length)];sync();renderRuleEditor(root)};$("#rule-cancel",root).onclick=()=>renderRuleSheet(root);$("#rule-save",root).onclick=()=>{state.rule={...r};state.ruleName="自造纹法";saveComponent("R",{rule:r});updateCode();closeSheet()}}
function renderPaletteSheet(root){const saved=state.components.filter(x=>x.kind==="P");root.innerHTML=`<div class="sheet-section"><h4>经典色谱</h4><div class="option-grid">${BUILTIN_PALETTES.map(p=>`<button class="option ${state.palette.id===p.id?"active":""}" data-palette="${p.id}"><strong>${p.name}</strong><small>${p.colors.slice(1).join(" · ")}</small></button>`).join("")}</div></div><div class="sheet-section"><h4>我的色谱</h4>${saved.length?`<div class="option-grid">${saved.slice(-6).reverse().map(x=>`<button class="option" data-code="${x.code}"><strong>${escapeHtml(x.name)}</strong><small>${x.fp}</small></button>`).join("")}</div>`:"<div class='empty'>还没有自造色谱</div>"}<button class="sheet-create" id="create-palette">＋ 造一套色谱</button></div>`;$$('[data-palette]',root).forEach(b=>b.onclick=()=>{const p=BUILTIN_PALETTES.find(x=>x.id===b.dataset.palette);state.palette={id:p.id,name:p.name,colors:[...p.colors],custom:false};updateCode();syncMeta();schedule();renderPaletteSheet(root)});$$('[data-code]',root).forEach(b=>b.onclick=()=>{applyDecoded(decodeObject(b.dataset.code),false);renderPaletteSheet(root)});$("#create-palette",root).onclick=()=>renderPaletteEditor(root)}
function renderPaletteEditor(root){const colors=[...state.palette.colors];root.innerHTML=`<div class="palette-editor">${["纸色","主色","辅色","点色"].map((n,i)=>`<div class="color-field"><label>${n}<input data-color="${i}" type="color" value="${colors[i]}"></label></div>`).join("")}</div><button class="sheet-create" id="auto-palette">✦ 给我配一套</button><div class="sheet-footer"><button class="ghost" id="palette-back">返回</button><button class="primary" id="palette-save">存为我的色谱</button></div>`;const sync=()=>{state.palette={id:"custom",name:"自造色谱",colors:[...colors],custom:true};updateCode();syncMeta();schedule()};$$('[data-color]',root).forEach(el=>el.oninput=()=>{colors[Number(el.dataset.color)]=el.value;sync()});$("#auto-palette",root).onclick=()=>{const hue=Math.floor(Math.random()*360),hsl=(h,s,l)=>{const a=s*Math.min(l,1-l)/100,f=n=>{const k=(n+h/30)%12;return l/100-a*Math.max(-1,Math.min(k-3,9-k,1))},x=n=>Math.round(255*f(n)).toString(16).padStart(2,"0");return`#${x(0)}${x(8)}${x(4)}`};colors[0]=hsl(hue,22,92);colors[1]=hsl(hue,40,32);colors[2]=hsl((hue+150)%360,35,36);colors[3]=hsl((hue+38)%360,48,55);sync();renderPaletteEditor(root)};$("#palette-back",root).onclick=()=>renderPaletteSheet(root);$("#palette-save",root).onclick=()=>{state.palette={id:"custom",name:"自造色谱",colors:[...colors],custom:true};saveComponent("P",{palette:state.palette});updateCode();closeSheet()}}
function renderShareSheet(root){root.innerHTML=`<div class="share-options"><button id="share-work"><strong>发作品</strong><small>导出 3:4 图片，并复制带万象码的分享文案</small></button><button id="share-challenge"><strong>发起「同笔不同纹」</strong><small>锁定你的笔势，让朋友换纹元、纹法和色谱</small></button><button id="share-rule"><strong>只分享当前纹法</strong><small>朋友导入后可以直接套到自己的作品</small></button><button id="share-motif"><strong>只分享当前纹元</strong><small>把你画的纹元变成可复制组件</small></button><button id="share-palette"><strong>只分享当前色谱</strong><small>分享配色，不改变朋友的其它规则</small></button></div>`;$("#share-work",root).onclick=async()=>{await exportImage();await copyText(makeShareText(state.code,"自由 Remix"));toast("作品已成图，万象码文案已复制")};$("#share-challenge",root).onclick=async()=>{const code=encodeObject(TYPES.H,{...currentObj(),lockMask:1});await copyText(makeShareText(code,"同笔不同纹"));toast("挑战码已复制")};$("#share-rule",root).onclick=()=>copyComponent("R");$("#share-motif",root).onclick=()=>copyComponent("M");$("#share-palette",root).onclick=()=>copyComponent("P")}
async function copyComponent(k){const type=TYPES[k],code=encodeObject(type,componentObj(type));await copyText(code);toast(`${k==="R"?"纹法":k==="M"?"纹元":"色谱"}万象码已复制`)}
function makeShareText(code,challenge){return`我画了一笔，它长成了这一纹。\n\n纹脉：${state.fingerprint}\n${challenge?`挑战：${challenge}\n`:""}复制下面的万象码，打开《纹生万象》导入即可 Remix：\n${code}`}

async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{const ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();const ok=document.execCommand("copy");ta.remove();return ok}}
async function exportImage(){if(!state.stroke.length)return;state.mode="EXPORTING";await new Promise(requestAnimationFrame);const out=document.createElement("canvas");out.width=900;out.height=1200;const snap={stroke:state.stroke,motif:state.motif,rule:state.rule,palette:state.palette,code:state.code,fingerprint:state.fingerprint};paint(out,snap,1,true);const blob=await new Promise(r=>out.toBlob(r,"image/png"));const xhs=window.xhs?.miniTool;try{if(xhs?.saveImage){await xhs.saveImage(out.toDataURL("image/png"));toast("图片已保存")}else{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`纹生万象-${state.fingerprint}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("PNG 已导出")}}catch{toast("保存失败，请重试")}out.width=1;out.height=1;state.mode="READY"}

function renderComponents(filter=""){const list=$("#component-list"),items=state.components.filter(x=>!filter||x.kind===filter).slice(-12).reverse();list.innerHTML=items.length?items.map((x,i)=>`<div class="component-card"><div class="component-thumb">${x.kind==="S"?"～":x.kind==="M"?"◇":x.kind==="R"?"⌘":"●"}</div><div><strong>${escapeHtml(x.name)}</strong><small>${x.kind} · ${x.fp}</small></div><div class="mini-actions"><button data-apply-index="${state.components.indexOf(x)}" aria-label="套用">↗</button><button data-copy-index="${state.components.indexOf(x)}" aria-label="复制">⧉</button></div></div>`).join(""):"<div class='empty'>工坊还是空的。先从一幅作品里创造自己的组件吧。</div>";$$('[data-apply-index]',list).forEach(b=>b.onclick=()=>{try{applyDecoded(decodeObject(state.components[Number(b.dataset.applyIndex)].code),false)}catch{toast("组件损坏")}});$$('[data-copy-index]',list).forEach(b=>b.onclick=async()=>{await copyText(state.components[Number(b.dataset.copyIndex)].code);toast("万象码已复制")})}
function renderAtlas(){const list=$("#atlas-list");$("#atlas-count").textContent=`${state.atlas.length} 幅作品`;list.innerHTML="";if(!state.atlas.length){list.innerHTML="<div class='empty'>还没有收藏。造出喜欢的一纹后，点一次“收藏”即可。</div>";return}for(const item of state.atlas.slice().reverse()){const card=document.createElement("article");card.className="atlas-card";card.innerHTML=`<canvas width="240" height="320"></canvas><div class="atlas-card-info"><strong>${escapeHtml(item.name||"纹生万象")}</strong><small>纹脉 ${item.fp}</small></div><div class="atlas-card-actions"><button data-load>继续 Remix</button><button data-copy>复制码</button></div>`;list.appendChild(card);try{const o=decodeObject(item.code),snap={stroke:o.stroke,motif:o.motif,rule:o.rule,palette:o.palette,code:item.code,fingerprint:item.fp};paint(card.querySelector("canvas"),snap,1,false)}catch{}card.querySelector('[data-load]').onclick=()=>{try{applyDecoded(decodeObject(item.code),true)}catch{}};card.querySelector('[data-copy]').onclick=async()=>{await copyText(item.code);toast("万象码已复制")}}}
function switchView(v){state.view=v;$$('.view').forEach(el=>{const on=el.dataset.panel===v;el.hidden=!on;el.classList.toggle("active",on)});$$('[data-view]').forEach(b=>b.classList.toggle("active",b.dataset.view===v));if(v==="workshop")renderComponents();if(v==="atlas")renderAtlas();scrollTo({top:0,behavior:"smooth"})}
function importCode(){const input=$("#import-code"),box=$("#import-preview");try{const o=decodeObject(input.value);box.hidden=false;const typeName={1:"笔势",2:"纹元",3:"纹法",4:"色谱",5:"完整作品",6:"挑战"}[o.type];box.innerHTML=`<strong>✓ 识别成功：${typeName}</strong><br>纹脉 ${o.fingerprint}${o.legacy?" · 旧版 Seed 已兼容":""}<div class="sheet-footer"><button class="ghost" id="import-save">收入工坊</button><button class="primary" id="import-apply">立即 Remix</button></div>`;$("#import-apply",box).onclick=()=>applyDecoded(o,true);$("#import-save",box).onclick=()=>{if(o.type>=1&&o.type<=4){const kind=TYPE_CHARS[o.type];if(!state.components.some(x=>x.code===o.code))state.components.push({kind,code:o.code,name:`导入${typeName} · ${o.fingerprint}`,fp:o.fingerprint,createdAt:Date.now()});saveStore();renderComponents();toast("已收入万象工坊")}else toast("完整作品请在纹谱中收藏")}}catch(e){box.hidden=false;box.textContent=`无法导入：${e.message}`}}
function escapeHtml(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>el.classList.remove("show"),1500)}
function fitCanvas(){const dpr=Math.min(devicePixelRatio||1,1.6),cssW=$("#stage-wrap").clientWidth,quality=cssW<380?420:540,w=Math.min(Math.round(cssW*dpr),quality),h=Math.round(w*4/3);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;state.cache.planKey="";render(1)}}
function bind(){canvas.addEventListener("pointerdown",pointerDown);canvas.addEventListener("pointermove",pointerMove);canvas.addEventListener("pointerup",pointerUp);canvas.addEventListener("pointercancel",pointerUp);$("#demo-stroke").onclick=demo;$("#redraw").onclick=redraw;$("#inspire").onclick=inspire;$("#favorite").onclick=favorite;$("#copy-code").onclick=async()=>{if(!state.code)updateCode();await copyText(state.code);toast("万象码已带走")};$$('[data-sheet]').forEach(b=>b.onclick=()=>openSheet(b.dataset.sheet));$("#close-sheet").onclick=closeSheet;$("#sheet-backdrop").onclick=closeSheet;$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$("#import-btn").onclick=importCode;$("#import-code").onkeydown=e=>{if(e.key==="Enter")importCode()};$$('[data-maker]').forEach(b=>b.onclick=()=>{const map={stroke:"S",motif:"M",rule:"R",palette:"P"};$("#library-title").textContent=`我的${b.dataset.maker==="stroke"?"笔势":b.dataset.maker==="motif"?"纹元":b.dataset.maker==="rule"?"纹法":"色谱"}`;renderComponents(map[b.dataset.maker])});$("#show-all-components").onclick=()=>{$("#library-title").textContent="最近创作";renderComponents()};$("#clear-atlas").onclick=()=>{if(confirm("只清空本机纹谱，不影响你已经复制出去的万象码。确定吗？")){state.atlas=[];saveStore();renderAtlas();toast("本地纹谱已清空")}};$("#open-info").onclick=()=>$("#info-dialog").showModal();$("#close-info").onclick=()=>$("#info-dialog").close();addEventListener("resize",()=>requestAnimationFrame(fitCanvas),{passive:true})}
function init(){loadStore();bind();fitCanvas();drawBlank();hideResult();renderComponents();renderAtlas();window.WenShengWanXiang={state,decode:decodeObject,encode:encodeObject,apply:applyDecoded,exportImage,benchmark(){const t0=performance.now();for(let i=0;i<100;i++){state.cache={strokeKey:"",model:null,planKey:"",plan:null};compilePlan(420,560)}return{iterations:100,ms:+(performance.now()-t0).toFixed(2)}}}}
init();
})();